---
title: Itsuporte
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
safe: false
lsi: false
highlighter: rouge
relative_source: "."
destination: "./_site"
username: itsuporte
repo: itsuporte.github.io
branch: master
exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- vendor
- ".travis.yml"
